name: Publish Docker Image
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
          - 'import <nixpkgs> {}'
          # - 'import <nixpkgs> { crossSystem.config = "aarch64-unknown-linux-gnu"; }'
        hub: [Github, Docker]
        include:
          - hub: Github
            registry: docker.pkg.github.com
            username: GH_USERNAME
            password: GITHUB_TOKEN
            image: "/matrix-registration-image"
          - hub: Docker
            registry: docker.io
            username: DOCKER_USERNAME
            password: DOCKER_PASSWORD
            image: ""
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - run: nix-build docker.nix --arg pkgs '${{ matrix.arch }}' --argstr tag ${{ env.VERSION }}
      - run: nix-env -i skopeo -f '<nixpkgs>'

      - name: Push to ${{ matrix.hub }} 
        run: |
          TAG=$GITHUB_REPOSITORY${{matrix.image}}:${{steps.tagName.outputs.tag}}
          sudo skopeo login --username="${{secrets[matrix.username]}}" --password="${{secrets[matrix.password]}}" ${{ matrix.registry }}
          sudo skopeo copy --insecure-policy docker-archive:result docker://${{ matrix.registry }}/$TAG
