name: Publish Docker Image
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      image: 

    strategy:
      matrix:
        arch:
          - 'import <nixpkgs> {}'
          # - 'import <nixpkgs> { crossSystem.config = "aarch64-unknown-linux-gnu"; }'
            
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - run: nix-build docker.nix --arg pkgs '${{ matrix.arch }}' --argstr tag ${{steps.tagName.outputs.tag}}

      - uses: actions/upload-artifact@master
        with:
          name: image
          path: result 

  push_to_registries:
    name: Push Docker Image to Multiple Registries
    runs-on: ubuntu-latest
    needs: build_image

    strategy:
      matrix:
        hub: [Github, Docker]
        include:
          - hub: Github
            registry: docker.pkg.github.com
            username: DOCKER_USERNAME
            password: GITHUB_TOKEN
            image: "/matrix-registration-image"
          - hub: Docker
            registry: docker.io
            username: DOCKER_USERNAME
            password: DOCKER_PASSWORD
            image: ""

    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - run: nix-env -i skopeo -f '<nixpkgs>'

      - uses: actions/download-artifact@master
        with:
          name: image

      - name: rename archive 
        run: mv result image.tar.gz

      - name: Push to ${{ matrix.hub }} 
        run: |
          sudo skopeo login --username="${{secrets[matrix.username]}}" --password="${{secrets[matrix.password]}}" ${{ matrix.registry }}
          sudo skopeo copy --insecure-policy docker-archive:image.tar.gz docker://${{matrix.registry}}/${GITHUB_REPOSITORY,,}${{matrix.image}}:${{steps.tagName.outputs.tag}}
